### PR TITLE
Rewrite README, minor improvements

### PR DESCRIPTION
**Pull request by Moire9**
Rewrite README, rewrite Rei vs. Luma, change support files to /em9/, if not there use /gm9, etc.

### CODE REVIEW

**Comment by Moire9** [comment]
@eiiiiix Okay, if the system does not see the /em9/support, then it will check for /gm9/support. It'll also check CTRNAND for both. This should be perfect to merge. If you don't have the time, I can merge it if you give me write access. Don't worry, I won't do anything bad ̶b̶e̶s̶i̶d̶e̶s̶ ̶g̶r̶i̶e̶f̶ ̶t̶h̶e̶ ̶r̶e̶p̶o̶s̶i̶t̶o̶r̶y̶. I can confirm stuff with you as well before. (Not like I can do anything major, not that good at C).

**Comment by eiiiiix** [comment]
firm payloads can only be upto 4mb in size
the data folder iirc (can't check rn) was borderline
the payload on its own is ~0.5mb or ~0.8mb meaning vram image needs to stay less than ~3.5mb or ~3.2mb
and rightnow it was borderline at that size because when making even a 0b file ~10kb or so are taken up
then you have spi/ntr payloads
those have to be installed to a cart but we have limited write space on those that can varry from 300kb to 2.6mb and sometimes upto 16mb
im not gonna merge until I can make sure whyrei.txt doesn't cause problems

**Comment by Moire9** [comment]
Okay. I'm trying to figure out how large /data is without downloading it.

**Comment by Moire9** [comment]
You know, Eix_Build_Commands.txt is basically a waste of space.
Just make a function or something.

**Comment by Moire9** [comment]
Here's a small function I made. Just copy it into ~/.bashrc
```
make_em9() {
     cd /home/eix/Desktop/GodMode9-master &> /dev/null
     export DEVKITARM=/home/eix/Desktop/devkitARM 
     export DEVKITPRO=/home/eix/Desktop/devkitpro 
     make EIXMODE=1 VERSION=
     make EIXMODE=1 NTRBOOT=1 VERSION=
     make SALTMODE=1 VERSION=
     make SALTMODE=1 NTRBOOT=1 VERSION=
     make VERSION=
     make NTRBOOT=1 VERSION=
     echo "Complete!"
}
```

**Comment by Moire9** [comment]
You'll probably want to fix the indents though if they're not the right size.

**Comment by eiiiiix** [comment]
using that you run into an issue
eixmode goes into /out
saltmode overwrites eixmode
normal overwrite salt

using that it would just build normal mode
you would need a way to seperate the builds
thats what i was trying to do when i screwed up the makefile

**Comment by Moire9** [comment]
I see. Let me think.

**Comment by Moire9** [comment]
```
make_em9() {
     cd /home/eix/Desktop/GodMode9-master &> /dev/null
     export DEVKITARM=/home/eix/Desktop/devkitARM &> /dev/null
     export DEVKITPRO=/home/eix/Desktop/devkitpro &> /dev/null
     make EIXMODE=1 VERSION=
     make EIXMODE=1 NTRBOOT=1 VERSION=
     cd out &> /dev/null
     mkdir norm && mv EixMode9.firm norm/EixMode9.firm &> /dev/null
     mv EixMode9_dev.firm norm/EixMode9_dev.firm &> /dev/null
     mv EixMode9_ntr_dev.firm norm/EixMode9_ntr_dev.firm &> /dev/null
     mv EixMode9_ntr.firm norm/EixMode9_ntr.firm &> /dev/null
     make SALTMODE=1 VERSION=
     make SALTMODE=1 NTRBOOT=1 VERSION=
     make VERSION=
     make NTRBOOT=1 VERSION=
     echo "Complete!"
}
```

**Comment by Moire9** [comment]
@eiiiiix okay, that should work.

**Comment by Moire9** [comment]
Just, figure it out, because that's wasting space in vram0.

**Comment by Moire9** [comment]
Come on, stop sleeping, Eix! Merge the pull!!
(lol I'm kidding)

**Comment by Moire9** [comment]
@eiiiiix last night I dreamed that you merged my pull. I'm not joking, I actually dreamed that. LOL!

**Comment by Moire9** [comment]
Okay, current commit has just under 2 MB in vram0. Merging should be safe.

**Comment by Moire9** [comment]
And Eix_Build_Commands.txt added in makes it just over 2 MB.

**Comment by eiiiiix** [comment]
im gonna merge but theres some stuff i want to change so ill fix later

**Pull request merged**
