### PR TITLE
GM9 commits

### PR DESCRIPTION
**Pull request by Moire9**
note: "Don" was supposed to be "Don't allow hexediting for empty/unreadable files" but my keyboard freaked out and made a phantom Enter keypress, so yeah....
More to come.

### CODE REVIEW

**Comment by Moire9** [comment]
Okay, these are all the important ones IMO. [p1] and [p2] and [p3] mean part 1 & part 2 & part 3 and [pf] means part final cuz i was too lazy to use git

**Comment by Moire9** [comment]
No reason to check RTC clock on NTRBoot because it's highly unlikelyto be setup and unimportant.

**Comment by Moire9** [comment]
Also, can I have contributer / maintainer role?

**Comment by Moire9** [comment]
Okay, latest commit broke it. I'll fix it as soon as possible.

**Comment by Moire9** [comment]
Okay, once again everything is merge-ready. Also did a small release.

**Comment by eiiiiix** [comment]
ok
thanks
took me a bit because i currently dont have easy access to stuff
but yeah i can give you a maintainer role

**Pull request merged**
